### ISSUE TITLE
python.analysis.stubPath

### ISSUE THREAD

**Issue by kevindawson** [cpwood/Pico-Stub#10]
> [python.analysis.stubPath](https://github.com/microsoft/pylance-release)

    Used to allow a user to specify a path to a directory that contains custom type stubs. Each package's type stub file(s) are expected to be in its own subdirectory.
    Default value: ./typings

Pylance - gets confused, Pin & ADC with out above
```python
from machine import Pin, ADC
```

settings.json
```json
{
  "python.linting.enabled": true,
  "python.analysis.typeshedPaths": [".vscode/Pico-Stub"],
  "python.analysis.stubPath": ".vscode/Pico-Stub",
  "python.languageServer": "Pylance",
  "python.analysis.typeCheckingMode": "basic",
  "python.analysis.extraPaths": [
    ".vscode/Pico-Stub/stubs"
  ],
  "python.pythonPath": "/home/*****/.local/share/virtualenvs/Pico_py-RF1i-mIK/bin/python"
}
```

**Comment by cpwood** [comment]
Hi @kevindawson - I either can't reproduce this or I'm not understanding correctly, sorry.

I've started a new Python file in Pico-Go and have configured the project so it's using the Pico-Stub stubs:

`settings.json` is as follows:

```json
{
    "python.linting.enabled": true,
    "python.analysis.typeshedPaths": [
        ".vscode/Pico-Stub"
    ],
    "python.languageServer": "Pylance",
    "python.analysis.typeCheckingMode": "basic",
    "python.analysis.extraPaths": [
        ".vscode/Pico-Stub/stubs"
    ]
}
```

First line of the Python file is:

```python
from machine import Pin, ADC
```

I don't see anything confusing; linting and intellisense all seem fine.

Also, `machine.pyi` is already in its own folder:

![image](https://user-images.githubusercontent.com/13966104/111082357-bac60a80-84ff-11eb-92ce-f0a1f5928964.png)

Sorry if I'm missing something; can you please clarify?

**Comment by kevindawson** [comment]
@cpwood 
pylint & mypy would be my first choice in pycharm. But that is not going to happen soon with rp2.

In vscode I have been having issues with linting & types after switching over to pylance - not my first choice but much easer to use due to your efforts.

rp2-pico-20210313-unstable-v1.14-108-ge98ff3f08.uf2

after re-reading pylance info on git hub I think you need to add the additional settings

there seamed to be an improvement 

nb. state.machines are still a pain in the rear at present regardless of which linter is used

the above is just sharing my **critique** with you

**Comment by cpwood** [comment]
If you'd prefer to use Pylint, [this](https://github.com/cpwood/Pico-Stub/blob/main/micropy.md#using-the-stubs) _should_ help. When the stubs _weren't_ part of Pico-Go, this is how I used to do it.

Regarding state machines, I know _exactly_ what you mean. [This](http://pico-go.net/docs/start/tips/#assembly-code-errors) is the best workaround for now, though [I'd prefer to be able to disable linting for a specific method](https://github.com/microsoft/pylance-release/issues/929#issuecomment-779152223). Not possible at the moment, unfortunately.

**Comment by kevindawson** [comment]
@cpwood 
I was going through that erk-sum process - hence switch to pylance due to your efforts

You need a link on GitHub front page -> http://pico-go.net/docs/start/tips

cool -> #assembly-code-errors - works great nice and quite on the lint errors now

I like a lot of others I expect will go to a projects GitHub as first place to look for info. or read the code works if I have too.
