### ISSUE TITLE
rp2 - machine.pyi irq

### ISSUE THREAD

**Issue by kevindawson** [cpwood/Pico-Stub#14]
silly fact - irq in machine and rp2 are different!
re: ` # def irq(self, lambdaFunction, direction: int):`

should be more like:
```python
    def irq(self, handler: Callable, trigger: int):
        """
        Sets an interrupt for when the pin is rising or falling.

            - ``handler`` lambdaFunction the code to execute when the interrupt happens.
            - ``trigger`` either ``IRQ_RISING`` or ``IRQ_FALLING``
        """
```
Thus linting: `pir.irq(handler=pir_handler, trigger=Pin.IRQ_RISING)` correctly

**Comment by kevindawson** [comment]
some test code from : https://github.com/raspberrypi/pico-micropython-examples/blob/master/irq/irq.py
```python
from machine import Pin

p2 = Pin(2, Pin.IN, Pin.PULL_UP)
p2.irq(lambda pin: print("IRQ with flags:", pin.irq().flags()), Pin.IRQ_FALLING)
```
or
```python
from machine import Pin

p2 = Pin(2, Pin.IN, Pin.PULL_UP)

def tp2(pin):
    print("IRQ with flags:", pin.irq().flags())

p2.irq( handler=tp2, trigger=Pin.IRQ_FALLING)
```
both forms work ok

**Comment by kevindawson** [comment]
@cpwood 
would you rather Pull Requests, as it looks like this is hand crafted - two steps ahead of the pack for rp2

**Comment by cpwood** [comment]
That would be amazing, thank you! I'll try and update the stubs in the Pico-Go extension over this weekend, God willing..!

**Comment by kevindawson** [comment]
@cpwood 

opps sorry for the noise - donkey - is a user name on homeNet - other wise it's all yours for now

**Comment by kevindawson** [comment]
see pull #15
