### ISSUE TITLE
Stubs v1.19.1

### ISSUE THREAD

**Issue by Wiz-IO** [cpwood/Pico-Stub#20]
Please generate Stubs for last version
rp2-pico-20220618-v1.19.1.uf2
https://micropython.org/resources/firmware/rp2-pico-20220618-v1.19.1.uf2

Thanks

BTW: I need only 
https://github.com/cpwood/Pico-Stub/tree/main/generated

**Comment by Wiz-IO** [comment]
![microPython](https://user-images.githubusercontent.com/14574834/197716572-0bdf7289-f64d-41ec-89b7-302e1f9f89ce.jpg)

**Comment by Josverl** [comment]
I do not Chris maintains this any longer.
rp2 and other stubs are available on PyPi : [micropython-rp2-stubs](https://github.com/Josverl/micropython-stubs#micropython-stubs) (multiple versions / firmwares) 
feel free to start a discussion / issue on the stubs repo if you miss anything

**Comment by Wiz-IO** [comment]
Thanks !
I found last version
