### ISSUE TITLE
Any command in the extention creates error

### ISSUE THREAD

**Issue by hasmar04** [cpwood/Pico-Stub#3]
`Command 'Pico-Go > Connect' resulted in an error (command 'pymakr.connect' not found)`
`Command 'Pico-Go > Help' resulted in an error (command 'pymakr.help' not found)`

Any command I try and run from the command pallete creates an error which mentions pymakr files. 

Made sure pymakr is uninstalled, checked that midejs is installed in pacman (arch linux), and tried uninstalling and reinstalling the extention. 

I followed your medium guide.

**Comment by cpwood** [comment]
Hi @hasmar04 . This isn't really a Pico-Stub issue; it's an issue with [Pico-Go](https://github.com/cpwood/Pico-Go/issues). Did you receive an error prior to this saying the extension wasn't compatible with your version of Visual Studio Code?

If you can submit an issue using the link above and provide the diagnostic information I'd need, I'll do my best to help. Note that the software only currently support x64 architectures at the moment, in case that's an issue. I'm working on adding arm64.

**Comment by hasmar04** [comment]
Apologies didn't realise it was a different repo. Will put a note there.
