### ISSUE TITLE
submit stubs to the micropython-stubs repo

### ISSUE THREAD

**Issue by Josverl** [cpwood/Pico-Stub#6]
Hi Chris,

I would like to invite you (also) to add the stubs to the [micropython-stubs](https://github.com/cpwood/Pico-Stub/blob/main/micropython-stubs)  repo , or if you prefer,  a referral to your own repo, to help others find the info.

TIA,
Jos

**Comment by Sadudu** [comment]
Hello, do you solve this problem? I also find there is no "stubs" folder in this repo.

**Comment by cpwood** [comment]
I'm sure I'll get to it, but haven't yet. 

Not sure it's dependent on me though either, if I understand correctly. Anybody could write something to sync the stubs from here with any other repo.

See the dist folder for the distributable stubs. There are two varieties available.

**Comment by Josverl** [comment]
@Chris ,

I see in your documentation that you are 'hand optimising' the stubs, which is great.
I would be interested to understand if/when you see that could be improved in the autogeneration , i.g. fixes that you need to make just about in each sub.
than i could try to include these in a next revision

**Comment by Josverl** [comment]
Chris, 
I have copied the stubs to the MicroPython-stubs repo, including your license and a short readme referring back to this repo.
I've set up an action that should keep things in sync, unless you change the structure significantly.

Thanks for the excellent work.
Jos
