### ISSUE TITLE
The UART constructor says it takes no arguments

### ISSUE THREAD

**Issue by 7west** [cpwood/Pico-Stub#7]
In VS Code it says the UART constructor takes no arguments, but when I run the command in REPL you need to include the UART index (0 or 1 on the Pico). According to this post the constructor for UART on Pico is different than the UART constructor for MicroPython: https://forum.micropython.org/viewtopic.php?f=2&t=9656. I could not find any other proof or documentation of this except that it works when I type it into the Pico with REPL

from machine import UART
uart = UART(0, 115200)    <<< VS Code says this line is wrong

Sorry if this issue isn't the most well researched, I am pretty new to python and Pico

**Comment by cpwood** [comment]
Thanks for the heads-up on this, @7west ! Pleased to say that this is now fixed and included within Pico-Go v1.2.0 too.

**Comment by 7west** [comment]
Thank you for developing such a useful VS Code extension!
